
import './globals.css'
import Navbar3 from '@/components/navbar'

export const metadata = {
  title: "Chirag's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
        <Navbar3/>
        {children}

      </body>
    </html>
  )
}
